
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;

public class InquireFrame extends javax.swing.JFrame {
    /**
     * Creates new form InquireFrame
     */
    protected EmployeeInfo currentEmp;
    protected MyHashTable currentHT;
    protected LandingPage currentLandingPage;
    
    public InquireFrame(EmployeeInfo cEmp, MyHashTable cHT, LandingPage cLP) {
        initComponents(); 
        currentEmp = cEmp;
        currentHT = cHT;
        currentLandingPage = cLP;
        modifyEN.setText(Integer.toString(currentEmp.getEmployeeNum()));
        modifyFN.setText(currentEmp.getFirstName());
        modifyLN.setText(currentEmp.getLastName());
        switch (currentEmp.getSex()) {
            case 0:
                editSexMale.setSelected(true);
                break;
            case 1:
                editSexFemale.setSelected(true);
                break;
            default:
                editSexOther.setSelected(true);
                break;
        }
        
        switch (currentEmp.getWorkLocation()) {
            case 0:
                editLocationMississauga.setSelected(true);
                break;
            case 1:
                editLocationOttawa.setSelected(true);
                break;
            default:
                editLocationChicago.setSelected(true);
                break;
        }
        modifyDR.setText(Double.toString(currentEmp.getDeductionRate()));
        if (currentEmp instanceof PartTimeEmployee){
            PartTimeEmployee initPartEmp = (PartTimeEmployee)currentEmp;
            modifyHW.setText(Double.toString(initPartEmp.getHourlyWage()));
            modifyHPW.setText(Integer.toString(initPartEmp.getHoursPerWeek()));
            modifyWPY.setText(Integer.toString(initPartEmp.getWeeksPerYear()));
            editPartTimeVSFullTime.setEnabled(true);
            editPartTimeVSFullTime.setEnabledAt(0, true);
            editPartTimeVSFullTime.setEnabledAt(1, false);
            editPartTimeVSFullTime.setSelectedIndex(0);
            editButtonPT.setSelected(true);
            
        }
        else{
            modifyYS.setText(Double.toString(((FullTimeEmployee)currentEmp).getYearlySalary()));
            editPartTimeVSFullTime.setEnabled(true);
            editPartTimeVSFullTime.setEnabledAt(0, false);
            editPartTimeVSFullTime.setEnabledAt(1, true);
            editPartTimeVSFullTime.setSelectedIndex(1);
            editButtonFT.setSelected(true);
        }
        cLP.setEnabled(false);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                currentLandingPage.setEnabled(true);
            }
        });
    }
    
    public boolean isStringInt(String s){
        try {
            Integer.parseInt(s);
            return true;
        } 
        catch (NumberFormatException ex){
            return false;
        }
    }
    
        public boolean isStringDouble(String s){
        try {
            Double.parseDouble(s);
            return true;
        } 
        catch (NumberFormatException ex){
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editEmpType = new javax.swing.ButtonGroup();
        editEmpSex = new javax.swing.ButtonGroup();
        editEmpLocation = new javax.swing.ButtonGroup();
        MissingEntries = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        InputErrorMsg = new javax.swing.JDialog();
        InputErrorMsgButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        EmployeeExistsError = new javax.swing.JDialog();
        EmployeeExistsDialog = new javax.swing.JLabel();
        modifyEN = new javax.swing.JTextField();
        modifyFN = new javax.swing.JTextField();
        modifyLN = new javax.swing.JTextField();
        editTitle = new javax.swing.JLabel();
        eNLabel = new javax.swing.JLabel();
        fNLabel = new javax.swing.JLabel();
        lNLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        modifyDR = new javax.swing.JTextField();
        sXLabel = new javax.swing.JLabel();
        wLLabel = new javax.swing.JLabel();
        dRLabel = new javax.swing.JLabel();
        editButtonPT = new javax.swing.JRadioButton();
        editButtonFT = new javax.swing.JRadioButton();
        editSexMale = new javax.swing.JRadioButton();
        editSexFemale = new javax.swing.JRadioButton();
        editSexOther = new javax.swing.JRadioButton();
        editLocationMississauga = new javax.swing.JRadioButton();
        editLocationOttawa = new javax.swing.JRadioButton();
        editLocationChicago = new javax.swing.JRadioButton();
        editPartTimeVSFullTime = new javax.swing.JTabbedPane();
        editPartTimeTab = new javax.swing.JPanel();
        hWLabel = new java.awt.Label();
        modifyHW = new java.awt.TextField();
        hPWLabel = new java.awt.Label();
        modifyHPW = new java.awt.TextField();
        wPYLabel = new java.awt.Label();
        modifyWPY = new java.awt.TextField();
        editFullTimeTab = new javax.swing.JPanel();
        modifyYS = new java.awt.TextField();
        ySLabel = new java.awt.Label();

        MissingEntries.setMinimumSize(new java.awt.Dimension(300, 200));
        MissingEntries.setResizable(false);

        jLabel3.setText("Error! Please make sure all entries are filled out!");

        javax.swing.GroupLayout MissingEntriesLayout = new javax.swing.GroupLayout(MissingEntries.getContentPane());
        MissingEntries.getContentPane().setLayout(MissingEntriesLayout);
        MissingEntriesLayout.setHorizontalGroup(
            MissingEntriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MissingEntriesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        MissingEntriesLayout.setVerticalGroup(
            MissingEntriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MissingEntriesLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel3)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        InputErrorMsg.setMinimumSize(new java.awt.Dimension(272, 207));
        InputErrorMsg.setResizable(false);

        InputErrorMsgButton.setText("Got it");
        InputErrorMsgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputErrorMsgButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Error! Please check your input!");

        javax.swing.GroupLayout InputErrorMsgLayout = new javax.swing.GroupLayout(InputErrorMsg.getContentPane());
        InputErrorMsg.getContentPane().setLayout(InputErrorMsgLayout);
        InputErrorMsgLayout.setHorizontalGroup(
            InputErrorMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputErrorMsgLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(InputErrorMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(InputErrorMsgLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(InputErrorMsgButton)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        InputErrorMsgLayout.setVerticalGroup(
            InputErrorMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputErrorMsgLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(InputErrorMsgButton)
                .addGap(60, 60, 60))
        );

        EmployeeExistsError.setMinimumSize(new java.awt.Dimension(300, 200));
        EmployeeExistsError.setResizable(false);

        EmployeeExistsDialog.setText("Error! Employee already exists!");

        javax.swing.GroupLayout EmployeeExistsErrorLayout = new javax.swing.GroupLayout(EmployeeExistsError.getContentPane());
        EmployeeExistsError.getContentPane().setLayout(EmployeeExistsErrorLayout);
        EmployeeExistsErrorLayout.setHorizontalGroup(
            EmployeeExistsErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeExistsErrorLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(EmployeeExistsDialog)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        EmployeeExistsErrorLayout.setVerticalGroup(
            EmployeeExistsErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeExistsErrorLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(EmployeeExistsDialog)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        modifyEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyENActionPerformed(evt);
            }
        });

        modifyFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyFNActionPerformed(evt);
            }
        });

        modifyLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyLNActionPerformed(evt);
            }
        });

        editTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        editTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editTitle.setText("Employee Edit");

        eNLabel.setText("Emplyoee Num");

        fNLabel.setText("First Name");

        lNLabel.setText("Last Name");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        modifyDR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyDRActionPerformed(evt);
            }
        });

        sXLabel.setText("Sex");

        wLLabel.setText("Work Location");

        dRLabel.setText("Deduction Rate");

        editEmpType.add(editButtonPT);
        editButtonPT.setText("Part-Time");
        editButtonPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonPTActionPerformed(evt);
            }
        });

        editEmpType.add(editButtonFT);
        editButtonFT.setText("Full-Time");
        editButtonFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonFTActionPerformed(evt);
            }
        });

        editEmpSex.add(editSexMale);
        editSexMale.setText("Male");
        editSexMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSexMaleActionPerformed(evt);
            }
        });

        editEmpSex.add(editSexFemale);
        editSexFemale.setText("Female");

        editEmpSex.add(editSexOther);
        editSexOther.setText("Other");

        editEmpLocation.add(editLocationMississauga);
        editLocationMississauga.setText("Mississauga");

        editEmpLocation.add(editLocationOttawa);
        editLocationOttawa.setText("Ottawa");

        editEmpLocation.add(editLocationChicago);
        editLocationChicago.setText("Chicago");

        editPartTimeVSFullTime.setEnabled(false);

        hWLabel.setText("Hourly Wage");

        hPWLabel.setText("Hours Per Week");

        wPYLabel.setText("Weeks Per Year");

        javax.swing.GroupLayout editPartTimeTabLayout = new javax.swing.GroupLayout(editPartTimeTab);
        editPartTimeTab.setLayout(editPartTimeTabLayout);
        editPartTimeTabLayout.setHorizontalGroup(
            editPartTimeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPartTimeTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editPartTimeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wPYLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hWLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hPWLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(editPartTimeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modifyHW, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifyWPY, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifyHPW, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        editPartTimeTabLayout.setVerticalGroup(
            editPartTimeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPartTimeTabLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(editPartTimeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modifyHW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hWLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editPartTimeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hPWLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(editPartTimeTabLayout.createSequentialGroup()
                        .addComponent(modifyHPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editPartTimeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(modifyWPY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wPYLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        editPartTimeVSFullTime.addTab("Part-Time", editPartTimeTab);

        ySLabel.setText("Yearly Salary");

        javax.swing.GroupLayout editFullTimeTabLayout = new javax.swing.GroupLayout(editFullTimeTab);
        editFullTimeTab.setLayout(editFullTimeTabLayout);
        editFullTimeTabLayout.setHorizontalGroup(
            editFullTimeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editFullTimeTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ySLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modifyYS, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        editFullTimeTabLayout.setVerticalGroup(
            editFullTimeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editFullTimeTabLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(editFullTimeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modifyYS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ySLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        editPartTimeVSFullTime.addTab("Full-Time", editFullTimeTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sXLabel)
                            .addComponent(wLLabel)
                            .addComponent(dRLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(modifyDR, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(editSexMale)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(editSexFemale)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(editSexOther))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(editLocationMississauga)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(editLocationOttawa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(editLocationChicago)))
                                .addGap(0, 96, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(eNLabel)
                                    .addComponent(fNLabel)
                                    .addComponent(lNLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(modifyFN)
                                    .addComponent(modifyLN)
                                    .addComponent(modifyEN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(editPartTimeVSFullTime, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(editButtonPT)
                        .addGap(59, 59, 59)
                        .addComponent(editButtonFT))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(saveButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(editTitle)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eNLabel)
                    .addComponent(modifyEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNLabel)
                    .addComponent(modifyFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNLabel)
                    .addComponent(modifyLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sXLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wLLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editSexMale)
                            .addComponent(editSexFemale)
                            .addComponent(editSexOther))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editLocationMississauga)
                            .addComponent(editLocationOttawa)
                            .addComponent(editLocationChicago))))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dRLabel)
                    .addComponent(modifyDR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButtonPT)
                    .addComponent(editButtonFT))
                .addGap(18, 18, 18)
                .addComponent(editPartTimeVSFullTime, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(deleteButton))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modifyENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyENActionPerformed
    }//GEN-LAST:event_modifyENActionPerformed

    private void modifyFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyFNActionPerformed
    }//GEN-LAST:event_modifyFNActionPerformed

    private void modifyLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyLNActionPerformed
    }//GEN-LAST:event_modifyLNActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        boolean entryError = false;       
        String editENEntry = modifyEN.getText();
        int saveEN = 0;
        if (isStringInt(editENEntry) == true){
            saveEN = Integer.parseInt(modifyEN.getText());
        }
        else {
            entryError = true;
        }
        for (int i=0; i<currentHT.bucketCount; ++i){
            ArrayList<EmployeeInfo> currentAList = currentHT.buckets[i];
            for (int k=0; k<currentAList.size(); ++k){
                if (saveEN != currentEmp.getEmployeeNum() && saveEN == currentAList.get(k).getEmployeeNum()){
                    EmployeeExistsError.setVisible(true);
                    return;
                }
            }
        }
        String saveFN = modifyFN.getText();
        String saveLN = modifyLN.getText();
        
        String editEDEntry = modifyDR.getText();
        double saveDR = 0;
        if (isStringDouble(editEDEntry) == true){
            saveDR = Double.parseDouble(modifyDR.getText());
        }
        else {
            entryError = true;
        }
        
        boolean entriesAreGood = false;
        
        if (editENEntry.isEmpty() || saveFN.isEmpty() || saveLN.isEmpty() || editEDEntry.isEmpty()){
            entriesAreGood = false;
        }
        else {
            entriesAreGood = true;
        }
        
        int saveSX = 0;
        int saveWL = 0;
        
        if (editSexMale.isSelected()){
            saveSX = 0;
        }
        else if (editSexFemale.isSelected()){
            saveSX = 1;
        }
        else {
            saveSX = 2;
        }
        
        boolean sexSelected = false;
        if (editSexMale.isSelected() || editSexFemale.isSelected() || editSexOther.isSelected()){
            sexSelected = true;
        }
        
        if (editLocationMississauga.isSelected()){
            saveWL = 0;
        }
        else if (editLocationOttawa.isSelected()){
            saveWL = 1;
        }
        else {
            saveWL = 2;
        }
        
        boolean locationSelected = false;
        if (editLocationMississauga.isSelected() || editLocationOttawa.isSelected() || editLocationChicago.isSelected()){
            locationSelected = true;
        }
        
        boolean jobStatus = false;
        if (editButtonPT.isSelected() || editButtonFT.isSelected()){
            jobStatus = true;
        }
        
        boolean partTimeEntry = false;
        boolean fullTimeEntry = false;
        
        double saveHW = 0;
        int saveHPW = 0;
        int saveWPY = 0;
        double saveYS = 0;

        if (editButtonPT.isSelected()){
            String editHWEntry = modifyHW.getText();
            if (isStringDouble(editHWEntry) == true){
                saveHW = Double.parseDouble(modifyHW.getText());
            }
            else {
                entryError = true;
            }
        
            String editHPWEntry = modifyHPW.getText();
            if (isStringInt(editHPWEntry) == true){
                saveHPW = Integer.parseInt(modifyHPW.getText());
            }
            else {
                entryError = true;
            }
        
            String editWPYEntry = modifyWPY.getText();
            if (isStringInt(editWPYEntry) == true){
                saveWPY = Integer.parseInt(modifyWPY.getText());
            }
            else {
                entryError = true;
            }
            
            if (editHWEntry.isEmpty() || editHPWEntry.isEmpty() || editWPYEntry.isEmpty()){
                partTimeEntry = false;
            }
            else {
                partTimeEntry = true;
            }
        }
        else if (editButtonFT.isSelected()){
            String editYSEntry = modifyYS.getText();
            if (isStringDouble(editYSEntry) == true){
                saveYS = Double.parseDouble(modifyYS.getText());
                fullTimeEntry = true;
            }
            else if (!editYSEntry.equals("")){
                fullTimeEntry = true;
            }
            else {
                entryError = true;
            }
        }

        boolean workEntry = false;
        if (partTimeEntry == true || fullTimeEntry == true){
            workEntry = true;
        }
        
        boolean everythingOK = false;
        if (entriesAreGood == true && sexSelected == true && locationSelected == true && jobStatus == true && workEntry == true){
            everythingOK = true;
        }
        
        if (everythingOK == false){
            MissingEntries.setVisible(true);
            entryError = false;
        }

        else if (entryError){
            InputErrorMsg.setVisible(true);
        }
        
        else if (everythingOK){          
            currentHT.removeEmployee(currentEmp.getEmployeeNum());
            if (editButtonPT.isSelected()){
                currentHT.addEmployee(new PartTimeEmployee(saveEN, saveFN, saveLN, saveSX, saveWL, saveDR, saveHW, saveHPW, saveWPY));
            }
            else{
                currentHT.addEmployee(new FullTimeEmployee(saveEN, saveFN, saveLN, saveSX, saveWL, saveDR, saveYS));
            }
        }
        currentLandingPage.setEnabled(true);
        this.setVisible(false);
        currentLandingPage.callRefreshButton(evt);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        currentHT.removeEmployee(currentEmp.getEmployeeNum());
        currentLandingPage.setEnabled(true);
        this.setVisible(false);
        currentLandingPage.callRefreshButton(evt);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void modifyDRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyDRActionPerformed
    }//GEN-LAST:event_modifyDRActionPerformed

    private void editSexMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSexMaleActionPerformed
    }//GEN-LAST:event_editSexMaleActionPerformed

    private void editButtonPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonPTActionPerformed
        editPartTimeVSFullTime.setEnabled(true);
        editPartTimeVSFullTime.setEnabledAt(1, true);
        editPartTimeVSFullTime.setEnabledAt(1, false);
        editPartTimeVSFullTime.setSelectedIndex(0);
        modifyYS.setText("");
    }//GEN-LAST:event_editButtonPTActionPerformed

    private void editButtonFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonFTActionPerformed
        editPartTimeVSFullTime.setEnabled(true);
        editPartTimeVSFullTime.setEnabledAt(0, false);
        editPartTimeVSFullTime.setEnabledAt(1, true);
        editPartTimeVSFullTime.setSelectedIndex(1);
        modifyHW.setText("");
        modifyHPW.setText("");
        modifyWPY.setText("");
    }//GEN-LAST:event_editButtonFTActionPerformed

    private void InputErrorMsgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputErrorMsgButtonActionPerformed
        InputErrorMsg.setVisible(false);
    }//GEN-LAST:event_InputErrorMsgButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmployeeExistsDialog;
    private javax.swing.JDialog EmployeeExistsError;
    private javax.swing.JDialog InputErrorMsg;
    private javax.swing.JButton InputErrorMsgButton;
    private javax.swing.JDialog MissingEntries;
    private javax.swing.JLabel dRLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel eNLabel;
    private javax.swing.JRadioButton editButtonFT;
    private javax.swing.JRadioButton editButtonPT;
    private javax.swing.ButtonGroup editEmpLocation;
    private javax.swing.ButtonGroup editEmpSex;
    private javax.swing.ButtonGroup editEmpType;
    private javax.swing.JPanel editFullTimeTab;
    private javax.swing.JRadioButton editLocationChicago;
    private javax.swing.JRadioButton editLocationMississauga;
    private javax.swing.JRadioButton editLocationOttawa;
    private javax.swing.JPanel editPartTimeTab;
    private javax.swing.JTabbedPane editPartTimeVSFullTime;
    private javax.swing.JRadioButton editSexFemale;
    private javax.swing.JRadioButton editSexMale;
    private javax.swing.JRadioButton editSexOther;
    private javax.swing.JLabel editTitle;
    private javax.swing.JLabel fNLabel;
    private java.awt.Label hPWLabel;
    private java.awt.Label hWLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lNLabel;
    private javax.swing.JTextField modifyDR;
    private javax.swing.JTextField modifyEN;
    private javax.swing.JTextField modifyFN;
    private java.awt.TextField modifyHPW;
    private java.awt.TextField modifyHW;
    private javax.swing.JTextField modifyLN;
    private java.awt.TextField modifyWPY;
    private java.awt.TextField modifyYS;
    private javax.swing.JLabel sXLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel wLLabel;
    private java.awt.Label wPYLabel;
    private java.awt.Label ySLabel;
    // End of variables declaration//GEN-END:variables
}
